/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import org.main.App;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
    }
}
